Update rpi-setup-tool

diff --git a/rpi-setup-tool b/rpi-setup-tool
--- a/rpi-setup-tool
+++ b/rpi-setup-tool
@@ -35,6 +35,40 @@ pink=`tput setaf 57`
 blue=`tput setaf 27 bold`
 
 #Main Script
+echo "${blue}Updating Repository List...${std}"
+sudo apt-get update
+echo ""
+echo "${blue}Repository List updated! Continuing Installation!${std}"
+sleep 1
+
+echo ""
+echo ""
+echo "${green}It is highly recommended to update your OS before Installation!${std}"
+echo "${green}Do you want to update your OS?${std}"
+echo ""
+read -p "${green}Yes (y)/ No (n): ${std}" n;
+
+while ! [[ "$n" =~ ^(y|n)$ ]];
+do
+        echo ""
+        echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
+        read -p "Yes (y)/ No (n): " n;
+done
+
+if [[ "$n" =~ ^(y)$ ]];
+then
+        echo ""
+        echo "${blue}Updating the OS now...${std}"
+	sudo apt-get upgrade -y
+        echo ""
+        echo "${blue}Operating System updated successfully! Continuing the Installation!${std}"
+        sleep 1
+else
+        echo ""
+        echo "${red}Not updating your OS! Installation might fail!${std}"
+	sleep 1
+fi
+
 echo ""
 echo ""
 echo "${blue}      ////////////  ////////////  //////   ////////////  ////////////${std}"
@@ -108,43 +142,3 @@ echo ""
 echo "${blue}Operating System okay! Continuing the Installation!${std}"
 sleep 1
 
-echo ""
-echo ""
-echo "${blue}Updating Repository List...${std}"
-
-sudo apt-get update
-
-echo ""
-echo "${blue}Repository List updated! Continuing Installation!${std}"
-sleep 1
-
-echo ""
-echo ""
-echo "${green}It is highly recommended to update your OS before Installation!${std}"
-echo "${green}Do you want to update your OS?${std}"
-
-echo ""
-read -p "${green}Yes (y)/ No (n): ${std}" n;
-
-while ! [[ "$n" =~ ^(y|n)$ ]];
-do
-        echo ""
-        echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
-        read -p "Yes (y)/ No (n): " n;
-done
-
-if [[ "$n" =~ ^(y)$ ]];
-then
-        echo ""
-        echo "${blue}Updating the OS now...${std}"
-
-	sudo apt-get upgrade -y
-
-        echo ""
-        echo "${blue}Operating System updated successfully! Continuing the Installation!${std}"
-        sleep 1
-else
-        echo ""
-        echo "${red}Not updating your OS! Installation might fail!${std}"
-	sleep 1
-fi
