Added check if Systemclock is in Sync and NTP Server Setup

diff --git a/rpi-setup-tool b/rpi-setup-tool
--- a/rpi-setup-tool
+++ b/rpi-setup-tool
@@ -53,6 +53,105 @@ clear_arrays () {
 	UNUSED_PACKAGE_ARRAY=()
 }
 
+check_clocksync () {
+	SYNC=$(sudo timedatectl | grep "synchronized")
+	if [[ "$SYNC" == *"no" ]]
+	then
+		SYNC=0
+	elif [[ "$SYNC" == *"yes" ]]
+	then
+		SYNC=1
+	else
+		SYNC=2
+	fi
+}
+
+check_clocksync_verbose () {
+	echo "${blue}Checking Sync Status of the Systemclock, this could take up to 2 minutes!${std}"
+	echo "${blue}Checking Sync Status of the Systemclock${std}"
+	timeout=240
+	counter=1
+	while [[ $SYNC -eq 0 || $timeout -ne 0 ]]
+	do
+		if [[ $counter == 1 ]]
+		then
+			echo -ne "${blue}Checking Sync Status of the Systemclock.${std}\r"
+		elif [[ $counter == 2 ]]
+		then
+			echo -ne "${blue}Checking Sync Status of the Systemclock..${std}\r"
+		elif [[ $counter == 3 ]]
+		then
+			echo -ne "${blue}Checking Sync Status of the Systemclock...${std}\r"
+			counter=1
+		fi
+		check_clocksync
+		counter=$($counter + 1)
+		timeout=$($timeout - 1)
+		sleep 0.5
+	done
+	echo -ne "${blue}Checking Sync Status of the Systemclock...${std}\r"
+	echo "${blue}Check finished!${std}"
+	echo ""
+	if [[ $SYNC == 1 ]]
+	then
+		echo "${green}The Systemclock is synchronized!${std}"
+	else
+		if [[ $SYNC == 2 ]]
+		then
+			echo "${red}Couldn't synchronize the Systemclock!${std}"
+			echo "${red}Exiting Script now!${std}"
+		else
+			echo "${red}There was an error while reading the Sync Status!${std}"
+			echo "${red}Exiting Script now!${std}"
+		fi
+		echo ""
+		sleep 1
+		exit
+	fi
+}
+
+setup_local_ntp () {
+	echo ""
+	echo "${green}Do you want to set the NTP Server IP manually or setup the Default Gateway?${std}"
+	echo ""
+	echo "1. Set IP to NTP Server manually"
+	echo "2. Fetch IP of the default Gateway"
+	echo ""
+	read -r -p "${green}Enter a Number for an Option: ${std}" n
+	while [[ $n -lt 1 || $n -gt 2 ]]
+	do
+			echo ""
+			echo "${red}Wrong Input! Please Select a Number for an Option!${std}"
+			read -r -p "Enter a Number for an Option: " n;
+	done
+	if [[ $n -eq 1 ]]
+	then
+			echo ""
+			read -r -p "${green}Enter the IP of the NTP Server: ${std}" ip_adress;
+			echo "${blue}Setting up the NTP Server within ${NTP} ...${std}"
+			sudo sed -i "s/^#NTP=.*/NTP=${ip_adress}/g" $NTP
+			sudo sed -i "s/^NTP=.*/NTP=${ip_adress}/g" $NTP
+			sudo sed -i "s/^#FallbackNTP=.*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/g" $NTP
+			sudo sed -i "s/^FallbackNTP=.*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/g" $NTP
+			sudo systemctl restart systemd-timesyncd.service
+			check_clocksync_verbose
+	else
+			echo ""
+			echo "${blue}Getting the default Gateway...${std}"
+			default_gateway=$(/sbin/ip route | awk '/default/ { print $3 }')
+			echo "$default_gateway"
+			echo "${blue}Setting up the NTP Server within ${NTP} ...${std}"
+			sudo sed -i "s/^#NTP=.*/NTP=${default_gateway}/g" $NTP
+			sudo sed -i "s/^NTP=.*/NTP=${default_gateway}/g" $NTP
+			sudo sed -i "s/^#FallbackNTP=.*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/g" $NTP
+			sudo sed -i "s/^FallbackNTP=.*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/g" $NTP
+			sudo systemctl restart systemd-timesyncd.service
+			check_clocksync_verbose
+	fi
+	echo ""
+	echo "${blue}Systemclock is now in Sync! Continuing the Installation!${std}"
+}
+
 set_possible_packages () {
 	if [[ $INSTALL_OPTIONS -eq 1 ]]
 	then
@@ -70,8 +169,6 @@ set_possible_packages () {
 		NO_WIFI=false
 		MNT_NAS=true
 		ISPBUSTER=false
-		SET_LOCALNTP=true
-
 
 	elif [[ $INSTALL_OPTIONS -eq 2 ]]
 	then
@@ -89,7 +186,6 @@ set_possible_packages () {
 		NO_WIFI=true
 		MNT_NAS=true
 		ISPBUSTER=true
-		SET_LOCALNTP=true
 
 	elif [[ $INSTALL_OPTIONS -eq 3 ]]
 	then
@@ -107,7 +203,6 @@ set_possible_packages () {
 		NO_WIFI=true
 		MNT_NAS=true
 		ISPBUSTER=true
-		SET_LOCALNTP=true
 	fi
 }
 
@@ -125,8 +220,7 @@ set_standard_packages () {
 		GPARTED=true
 		MNT_NAS=true
 		ISPBUSTER=false
-		SET_LOCALNTP=true
-		USED_PACKAGE_ARRAY=("RPI Config" "Kali VNC" "UCTronics LCD" "Netdrive Connector" "EEPROM Flasher" "Pishrink" "Samba" "GParted" "Mount NAS" "Local NTP")
+		USED_PACKAGE_ARRAY=("RPI Config" "Kali VNC" "UCTronics LCD" "Netdrive Connector" "EEPROM Flasher" "Pishrink" "Samba" "GParted" "Mount NAS")
 
 		#Packages that can't be installed
 		#EEPROM_UPDATE=false
@@ -145,8 +239,7 @@ set_standard_packages () {
 		NO_WIFI=true
 		MNT_NAS=false
 		ISPBUSTER=false
-		SET_LOCALNTP=true
-		USED_PACKAGE_ARRAY=("Update EEPROM" "UCTronics LCD" "Netdrive Connector" "Pishrink" "Samba" "Disable WIFI" "Local NTP")
+		USED_PACKAGE_ARRAY=("Update EEPROM" "UCTronics LCD" "Netdrive Connector" "Pishrink" "Samba" "Disable WIFI")
 		UNUSED_PACKAGE_ARRAY=("Mount NAS" "ISP Buster")
 
 		#Packages that can't be installed
@@ -169,8 +262,7 @@ set_standard_packages () {
 		NO_WIFI=true
 		MNT_NAS=true
 		ISPBUSTER=false
-		SET_LOCALNTP=true
-		USED_PACKAGE_ARRAY=("Update EEPROM" "UCTronics LCD" "Netdrive Connector" "Pishrink" "Samba" "GParted" "RPI Imager" "Disable WIFI" "Mount NAS" "Local NTP")
+		USED_PACKAGE_ARRAY=("Update EEPROM" "UCTronics LCD" "Netdrive Connector" "Pishrink" "Samba" "GParted" "RPI Imager" "Disable WIFI" "Mount NAS")
 		UNUSED_PACKAGE_ARRAY=("ISP Buster")
 
 		#Packages that can't be installed
@@ -483,32 +575,6 @@ select_custom_packages () {
 			UNUSED_PACKAGE_ARRAY+=("Mount NAS")
 		fi
 	fi
-
-	if $SET_LOCALNTP
-	then
-		echo ""
-		echo "${green}Fetch systemtime from a Local NTP Server?${std}"
-		echo ""
-		echo "${green}If your Firewall blocks vulnerable NTP Packets to the Internet${std}"
-		echo "${green}this machine won't be able to get the correct systemtime!${std}"
-		read -r -p "Yes (y)/ No (n): " n;
-
-		while ! [[ "$n" =~ ^(y|n)$ ]];
-		do
-			echo ""
-			echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
-			read -r -p "Yes (y)/ No (n): " n;
-		done
-
-		if [[ "$n" =~ ^(y)$ ]];
-		then
-			SET_LOCALNTP=true
-			USED_PACKAGE_ARRAY+=("Local NTP")
-		else
-			SET_LOCALNTP=false
-			UNUSED_PACKAGE_ARRAY+=("Local NTP")
-		fi
-	fi
 }
 
 show_packages_to_install () {
@@ -766,124 +832,12 @@ install_no_wifi () {
 	sleep 1
 }
 
-install_local_ntp () {
-	echo ""
-	echo ""
-	echo "${green}Do you want to set the NTP Server IP manually or setup the Default Gateway?${std}"
-	echo ""
-	echo "1. Set IP to NTP Server manually"
-	echo "2. Fetch IP of the default Gateway"
-	echo ""
-	read -r -p "${green}Enter a Number for an Option: ${std}" n
-
-	while [[ $n -lt 1 || $n -gt 2 ]]
-	do
-		echo ""
-		echo "${red}Wrong Input! Please Select a Number for an Option!${std}"
-		read -r -p "Enter a Number for an Option: " n;
-	done
-
-	if [[ $n -eq 1 ]]
-	then
-		echo ""
-		read -r -p "${green}Enter the IP of the NTP Server: ${std}" ip_adress;
-		echo "${blue}Checking if the Host is reachable...${std}"
-
-		if ping -c 1 "$ip_adress" &> /dev/null
-		then
-			echo "${blue}The Host is reachable!${std}"
-			i=1
-		else
-			i=0
-		fi
-
-		while [[ $i -eq 0 ]]
-		do
-			echo ""
-			echo "${red}The Host is not reachable! Please try a different IP!${std}"
-			read -r -p "Enter the IP of the NTP Server: " ip_adress;
-			echo ""
-			echo "${blue}Checking if the Host is reachable...${std}"
-
-			if ping -c 1 "$ip_adress" &> /dev/null
-			then
-				echo "${blue}The Host is reachable!${std}"
-				i=1
-			else
-				i=0
-			fi
-		done
-
-		echo "${blue}Setting up the NTP Server within ${NTP} ...${std}"
-		sudo sed -i "s/^#NTP=*/NTP=${ip_adress}/" $NTP
-		sudo sed -i "s/^NTP=*/NTP=${ip_adress}/" $NTP
-		sudo sed -i "s/^#FallbackNTP=*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/" $NTP
-		sudo sed -i "s/^FallbackNTP=*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/" $NTP
-		sudo systemctl restart systemd-timesyncd.service
-	else
-		echo ""
-		echo "${blue}Getting the default Gateway...${std}"
-		default_gateway=$(/sbin/ip route | awk '/default/ { print $3 }')
-		echo "$default_gateway"
-		echo "${blue}Checking if the default Gateway is reachable...${std}"
-		if ping -c 1 "$default_gateway" &> /dev/null
-		then
-			echo "${blue}Setting up the NTP Server within ${NTP} ...${std}"
-			sudo sed -i "s/^#NTP=*/NTP=${default_gateway}/" $NTP
-			sudo sed -i "s/^NTP=*/NTP=${default_gateway}/" $NTP
-			sudo sed -i "s/^#FallbackNTP=*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/" $NTP
-			sudo sed -i "s/^FallbackNTP=*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/" $NTP
-			sudo systemctl restart systemd-timesyncd.service
-		else
-			echo "${red}Default Gateway is not reachable! Please enter the IP of the NTP Server manually!${std}"
-			echo ""
-			read -r -p "${green}Enter the IP of the NTP Server: ${std}" ip_adress;
-			echo "${blue}Checking if the Host is reachable...${std}"
-
-			if ping -c 1 "$ip_adress" &> /dev/null
-			then
-				echo "${blue}The Host is reachable!${std}"
-				i=1
-			else
-				i=0
-			fi
-
-			while [[ $i -eq 0 ]]
-			do
-				echo ""
-				echo "${red}The Host is not reachable! Please try a different IP!${std}"
-				read -r -p "Enter the IP of the NTP Server: " ip_adress;
-				echo ""
-				echo "${blue}Checking if the Host is reachable...${std}"
-
-				if ping -c 1 "$ip_adress" &> /dev/null
-				then
-					echo "${blue}The Host is reachable!${std}"
-					i=1
-				else
-					i=0
-				fi
-			done
-
-			echo "${blue}Setting up the NTP Server within ${NTP} ...${std}"
-			sudo sed -i "s/^#NTP=*/NTP=${ip_adress}/" $NTP
-			sudo sed -i "s/^NTP=*/NTP=${ip_adress}/" $NTP
-			sudo sed -i "s/^#FallbackNTP=*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/" $NTP
-			sudo sed -i "s/^FallbackNTP=*/FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org/" $NTP
-			sudo systemctl restart systemd-timesyncd.service
-		fi
-	fi
-	echo ""
-	echo "${blue}Local NTP Server is setup successfully! Continuing the Installation!${std}"
-}
-
 install_mnt_nas () {
 	echo ""
 	echo ""
 	echo "${blue}Mounting NAS to ${NAS_DIR} Directory...${std}"
 	echo ""
 	echo "${blue}Checking ${NAS_DIR} Directory...${std}"
-
 	if [ -d "$NAS_DIR" ]
 	then
 		echo "${green}${NAS_DIR} Directory exists. Not Creating this Directory!${std}"
@@ -891,11 +845,9 @@ install_mnt_nas () {
 		echo "${blue}${NAS_DIR} Directory doesn't exist. Creating the Directory!${std}"
 		sudo mkdir -p $NAS_DIR
 	fi
-
 	echo ""
 	read -r -p "${green}Enter the IP of the NAS Server: ${std}" ip_adress;
 	echo "${blue}Checking if the Host is reachable...${std}"
-
 	if ping -c 1 "$ip_adress" &> /dev/null
 	then
 		echo "${blue}The Host is reachable!${std}"
@@ -903,7 +855,6 @@ install_mnt_nas () {
 	else
 		i=0
 	fi
-
 	while [[ $i -eq 0 ]]
 	do
 		echo ""
@@ -920,7 +871,6 @@ install_mnt_nas () {
 			i=0
 		fi
 	done
-
 	echo ""
 	read -r -p "${green}Enter the Sharename of the Drive: ${std}" sharename;
 	echo "${blue}The Sharename is:${std}"
@@ -944,14 +894,12 @@ install_mnt_nas () {
 		echo ""
 		echo "${green}Do you want to proceed?${std}"
 		read -r -p "Yes (y)/ No (n): " n;
-
 		while ! [[ "$n" =~ ^(y|n)$ ]];
 		do
 			echo ""
 			echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
 			read -r -p "Yes (y)/ No (n): " n;
 		done
-
 		if [[ "$n" =~ ^(y)$ ]];
 		then
 			echo ""
@@ -979,7 +927,6 @@ install_mnt_nas () {
 		echo "${blue}${NAS_DIR} Directory is empty!${std}"
 		echo "${blue}Appending the Code needed to mount the NAS to ${FSTAB} file...${std}"
 		echo "//${ip_adress}/${sharename} ${NAS_DIR} cifs username=${username},password=${password},defaults,nofail,_netdev,file_mode=0777,dir_mode=0777 0 0" | sudo tee -a $FSTAB > /dev/null
-
 		if sudo mount -a &> /dev/null
 		then
 			echo ""
@@ -1048,10 +995,55 @@ else
 	sleep 1
 	exit 1
 fi
-
 echo ""
 echo "${blue}Operating System okay! Continuing the Installation!${std}"
 sleep 1
+
+echo ""
+echo ""
+echo "${blue}Checking Systemclock Sync Status...${std}"
+echo ""
+check_clocksync
+if [[ $SYNC == 1 ]]
+then
+	echo "${green}The Systemclock is synchronized!${std}"
+else
+	if [[ $SYNC == 2 ]]
+	then
+		echo "${red}Couldn't synchronize the Systemclock!${std}"
+		echo ""
+		echo "${red}If your Firewall blocks vulnerable NTP Packets to the Internet${std}"
+		echo "${red}this machine won't be able to get the correct systemtime!${std}"
+		echo ""
+		echo ""
+		echo "${green}Fetch systemtime from a Local NTP Server?${std}"
+		echo ""
+		read -r -p "Yes (y)/ No (n): " n;
+		while ! [[ "$n" =~ ^(y|n)$ ]];
+		do
+			echo ""
+			echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
+			read -r -p "Yes (y)/ No (n): " n;
+		done
+		if [[ "$n" =~ ^(y)$ ]];
+		then
+			setup_local_ntp
+		else
+			echo ""
+			echo "${red}Couldn't synchronize the Systemclock!${std}"
+			echo "${red}Exiting Script now!${std}"
+			echo ""
+			sleep 1
+			exit
+		fi
+	else
+		echo "${red}There was an error while reading the Sync Status!${std}"
+		echo "${red}Exiting Script now!${std}"
+		echo ""
+		sleep 1
+		exit
+	fi
+fi
 
 echo ""
 echo ""
